#!/bin/bash

# Install a JupyterLab extension for demonstration purposes
# jupyter labextension install @jupyterlab/geojson-extension jupyterlab-drawio
# jupyter labextension install @jupyter-widgets/jupyterlab-manager 
# jupyter labextension install @jupyter-widgets/jupyter-leaflet
jupyter nbextension enable --py --sys-prefix ipyleaflet
# jupyter labextension install @bokeh/jupyter_bokeh
